import { createAsyncThunk } from "@reduxjs/toolkit";
import axios from "axios";
import {AxiosErrorHandler} from "@utils";
import { RootState } from "@store/index";

const actLikeToggle = createAsyncThunk(
  "wishlist/actLikeToggle",
  async (proId: number, thunkAPI) => {
    const { rejectWithValue, getState } = thunkAPI;
    const {auth} = getState() as RootState;
    try {
      const isRecordExist = await axios.get(
        `/wishlist?userId=${auth.user?.id}&productId=${proId}`
                                  //proId is ths id of the product itself "productId" in json server
      );
      if (isRecordExist.data.length > 0) {
        await axios.delete(`/wishlist/${isRecordExist.data[0].id}`);
                                                      //the id generated by json server
        return { type: "remove", proId };
      } else {
        await axios.post("/wishlist", { userId: auth.user?.id, productId: proId });
        return { type: "add", proId };
      }
    } catch (error) {
        return rejectWithValue(AxiosErrorHandler(error));
    }
  }
);
export default actLikeToggle;