import { createAsyncThunk } from "@reduxjs/toolkit";
import axios from "axios";
import {AxiosErrorHandler} from "@utils";

const actLikeToggle = createAsyncThunk(
  "wishlist/actLikeToggle",
  async (proId: number, thunkAPI) => {
    const { rejectWithValue } = thunkAPI;
    try {
      const isRecordExist = await axios.get(
        `/wishlist?userId=1&productId=${proId}`
                                  //proId is ths id of the product itself "productId" in json server
      );
      if (isRecordExist.data.length > 0) {
        await axios.delete(`/wishlist/${isRecordExist.data[0].id}`);
                                                      //the id generated by json server
        return { type: "remove", proId };
      } else {
        await axios.post("/wishlist", { userId: 1, productId: proId });
        return { type: "add", proId };
      }
    } catch (error) {
        return rejectWithValue(AxiosErrorHandler(error));
    }
  }
);
export default actLikeToggle;


